version: '3.9'

services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vehiclesdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  vehicles.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=vehiclesdb;user=appuser;password=apppassword
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - mysql

volumes:
  mysql_data:


version: '3.9'
services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env.development
  mysql:
    env_file:
      - .env.development
