version: '3.9'

services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - vehicles_network

  api:
    build:
      context: ./src/MinimalApi.Vehicles
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - mysql
    networks:
      - vehicles_network

volumes:
  mysql_data:

networks:
  vehicles_network:
    driver: bridge
